export default {
	'clear': 'sunny.png',
	'partly-cloudy': 'partly-cloudy.png',
	'variable-cloudiness': 'partly-cloudy.png',
	'cloudy-with-sunny-intervals': 'partly-cloudy.png',
	'cloudy': 'cloudy.png',
	'thunder': 'heavy-rain.png',
	'isolated-thunderstorms': 'thunderstorms.png',
	'thunderstorms': 'heavy-rain-with-thunderstorms.png',
	'heavy-rain-with-thunderstorms': 'heavy-rain-with-thunderstorms.png',
	'light-rain': 'light-rain.png',
	'rain': 'heavy-rain.png',
	'heavy-rain': 'heavy-rain.png',
	'rain-showers': 'heavy-rain.png',
	'light-rain-at-times': 'heavy-rain.png',
	'rain-at-times': 'heavy-rain.png',
	'light-sleet': 'light-rain.png',
	'sleet': 'sleet.png',
	'sleet-at-timest': 'sleet.png',
	'sleet-showerst': 'sleet.png',
	'freezing-rain': 'sleet.png',
	'hail': 'snowstorm.png',
	'light-snow': 'snow.png',
	'snow': 'snow.png',
	'heavy-snow': 'snowstorm.png',
	'snow-showers': 'snow.png',
	'snow-at-times': 'snow.png',
	'light-snow-at-times': 'snow.png',
	'snowstorm': 'snowstorm.png',
	'mist': 'fog.png',
	'fog':'fog.png',
	'squall': 'heavy-rain-with-thunderstorms.png',
};